### ISSUE TITLE
ZTEST_ZCL_PDF

### ISSUE THREAD

**Issue by larshp** [beraadim/zcl_pdf#2]
Hi,
The test report ZTEST_ZCL_PDF requires screen 0100 to work properly.

Can I submit a PR for the repository in abapGit format?

**Comment by beraadim** [comment]
Hi,

Yes of course - please do :)

I looked briefly on the abapGit client and it looked great! I will test it
as soon as I get the opertunity.


--BE

**Comment by beraadim** [comment]
Isssue should now have been resolved.
