### ISSUE TITLE
License

### ISSUE THREAD

**Issue by larshp** [beraadim/zcl_pdf#4]
Hi,
Can you help adding a license to let users know how/if they can use the code?

See
https://help.github.com/articles/adding-a-license-to-a-repository/
https://choosealicense.com/

**Comment by larshp** [comment]
@beraadim

**Comment by beraadim** [comment]
Sorry for the late response on this. License is now added.

**Comment by larshp** [comment]
thanks,

pull request is still open, https://github.com/beraadim/zcl_pdf/pull/5 not merged to master yet
